:toc: left
:icons: font
:nofooter:
:source-highlighter: coderay
:docinfo: shared,private

= SOAP Request/Response Logger

== Introduction

This is a `Spring Boot Starter` project which provides request/response logging for SOAP client applications.

== Usage



== Quick Start

Just add the dependency to your maven/gradle of your Spring Boot application then it will autoconfigure itself and _SOAP Logger_ will be available for all of your SOAP calls.

**Adding the dependency to your project**

```xml
<dependencies>
  <dependency>
    <groupId>com.github.kodgemisi</groupId>
    <artifactId>pooled-factory-bean</artifactId>
    <version>${pooled-factory-bean.version}</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
```

See https://jitpack.io/#kodgemisi/pooled-factory-bean for Jitpack usage, dependency details, version info and Gradle usage.

== Configuration


== Limitations


== License

© Copyright 2018 Kod Gemisi Ltd.

Mozilla Public License 2.0 (MPL-2.0)

link:https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)[]

MPL is a copyleft license that is easy to comply with. You must make the source code for any of your changes available under MPL, but you can combine the MPL software with proprietary code, as long as you keep the MPL code in separate files. Version 2.0 is, by default, compatible with LGPL and GPL version 2 or greater. You can distribute binaries under a proprietary license, as long as you make the source available under MPL.

https://www.mozilla.org/en-US/MPL/2.0/[See Full License Here]